import { useSQLiteContext } from 'expo-sqlite';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import Svg,{Circle} from 'react-native-svg';
import { AppScreen, Card, LoadingState, MoneyAmount, PageHeader } from '@/components/ui';
import { radius, spacing, useAppTheme } from '@/constants/theme';
import { useFinance } from '@/data/finance-context';
import { loadAnalytics,type AnalyticsSnapshot } from '@/data/repository';
import { addDays,today } from '@/domain/dates';
import { formatMoney } from '@/domain/money';

type Range='CYCLE'|'30D'|'MONTH'; const palette=['#176B55','#2866A9','#B87518','#8A5AA6','#C05F44','#4C8A9A','#7A8B45','#C04444'];
function nextMonthStart(d:string){const [y,m]=d.split('-').map(Number);const n=m===12?[y+1,1]:[y,m+1];return `${n[0]}-${String(n[1]).padStart(2,'0')}-01`}
export default function AnalyticsScreen(){const colors=useAppTheme();const db=useSQLiteContext();const {snapshot,error}=useFinance();const [range,setRange]=useState<Range>('CYCLE');const [data,setData]=useState<AnalyticsSnapshot|null>(null);const [loadError,setLoadError]=useState<string|null>(null);
 const dates=useMemo(()=>{if(!snapshot)return null;if(range==='CYCLE')return{start:snapshot.cycle.start,end:snapshot.cycle.end};if(range==='30D')return{start:addDays(today(),-29),end:addDays(today(),1)};const start=`${today().slice(0,7)}-01`;return{start,end:nextMonthStart(start)}},[range,snapshot]);
 useEffect(()=>{if(!dates)return;setData(null);loadAnalytics(db,dates.start,dates.end).then(setData).catch(e=>setLoadError(e instanceof Error?e.message:'统计失败'))},[db,dates]);
 if(!snapshot)return <AppScreen><LoadingState error={error}/></AppScreen>;if(!data)return <AppScreen><LoadingState error={loadError}/></AppScreen>;
 const hidden=!snapshot.settings.amountsVisible;const total=data.categories.reduce((s,x)=>s+x.amountMinor,0);const circumference=2*Math.PI*45;let offset=0;const maxDaily=Math.max(1,...data.daily.map(x=>Math.max(x.incomeMinor,x.expenseMinor)));
 return <AppScreen><PageHeader title="统计分析" subtitle={`${dates?.start} 至 ${addDays(dates!.end,-1)} · 按实际发生日期`}/><View style={styles.ranges}>{([['CYCLE','本周期'],['30D','近30天'],['MONTH','本月']] as [Range,string][]).map(([id,label])=><Pressable key={id} onPress={()=>setRange(id)} style={[styles.range,{backgroundColor:range===id?colors.primary:colors.surface,borderColor:colors.border}]}><Text style={{color:range===id?'#fff':colors.text,fontWeight:'800'}}>{label}</Text></Pressable>)}</View>
 <View style={styles.metrics}><Card style={styles.metric}><Text style={[styles.muted,{color:colors.textSecondary}]}>收入</Text><MoneyAmount value={data.totals.incomeMinor} hidden={hidden} size={20} color={colors.income}/></Card><Card style={styles.metric}><Text style={[styles.muted,{color:colors.textSecondary}]}>净支出</Text><MoneyAmount value={data.totals.netExpenseMinor} hidden={hidden} size={20} color={colors.expense}/></Card><Card style={styles.metric}><Text style={[styles.muted,{color:colors.textSecondary}]}>储蓄率</Text><Text style={[styles.big,{color:colors.text}]}>{hidden?'••••':`${(data.totals.savingsRate*100).toFixed(1)}%`}</Text></Card></View>
 <Card style={styles.card}><Text style={[styles.title,{color:colors.text}]}>支出构成</Text>{total>0?<View style={styles.chartRow}><Svg width={150} height={150} viewBox="0 0 120 120"><Circle cx="60" cy="60" r="45" fill="none" stroke={colors.surfaceMuted} strokeWidth="20"/>{data.categories.map((x,i)=>{const length=x.amountMinor/total*circumference;const node=<Circle key={x.name} cx="60" cy="60" r="45" fill="none" stroke={palette[i%palette.length]} strokeWidth="20" strokeDasharray={`${length} ${circumference-length}`} strokeDashoffset={-offset} rotation="-90" origin="60,60"/>;offset+=length;return node})}</Svg><View style={styles.legend}>{data.categories.slice(0,7).map((x,i)=><View key={x.name} style={styles.legendRow}><View style={[styles.dot,{backgroundColor:palette[i%palette.length]}]}/><Text style={[styles.legendName,{color:colors.text}]} numberOfLines={1}>{x.name}</Text><Text style={[styles.muted,{color:colors.textSecondary}]}>{hidden?'••••':`${(x.amountMinor/total*100).toFixed(1)}%`}</Text></View>)}</View></View>:<Text style={[styles.empty,{color:colors.textSecondary}]}>此范围暂无支出</Text>}</Card>
 <Card style={styles.card}><Text style={[styles.title,{color:colors.text}]}>每日收支</Text>{data.daily.length?<View style={styles.bars}>{data.daily.slice(-14).map(x=><View key={x.date} style={styles.day}><View style={styles.barPair}><View style={[styles.bar,{height:Math.max(2,x.incomeMinor/maxDaily*100),backgroundColor:colors.income}]}/><View style={[styles.bar,{height:Math.max(2,Math.max(0,x.expenseMinor)/maxDaily*100),backgroundColor:colors.expense}]}/></View><Text style={[styles.dayText,{color:colors.textSecondary}]}>{x.date.slice(5)}</Text></View>)}</View>:<Text style={[styles.empty,{color:colors.textSecondary}]}>此范围暂无收支记录</Text>}<Text style={[styles.muted,{color:colors.textSecondary}]}>绿色为收入，红色为扣除退款后的净支出；转账不属于收支。</Text></Card>
 <Card style={styles.card}><Text style={[styles.title,{color:colors.text}]}>计算说明</Text><Text style={[styles.empty,{color:colors.textSecondary}]}>毛支出 {hidden?'••••':formatMoney(data.totals.grossExpenseMinor)} · 退款 {hidden?'••••':formatMoney(data.totals.refundMinor)}。储蓄率 =（收入 − 净支出）÷ 收入。</Text></Card>
 </AppScreen>}
const styles=StyleSheet.create({ranges:{flexDirection:'row',gap:spacing.sm},range:{flex:1,minHeight:44,borderWidth:1,borderRadius:radius.pill,alignItems:'center',justifyContent:'center'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},metric:{flexGrow:1,minWidth:105,gap:spacing.sm},muted:{fontSize:12},big:{fontSize:20,fontWeight:'900'},card:{gap:spacing.lg},title:{fontSize:18,fontWeight:'900'},chartRow:{flexDirection:'row',alignItems:'center',gap:spacing.md},legend:{flex:1,gap:spacing.sm},legendRow:{flexDirection:'row',alignItems:'center',gap:spacing.sm},dot:{width:9,height:9,borderRadius:5},legendName:{flex:1,fontSize:13,fontWeight:'700'},empty:{fontSize:13,lineHeight:20},bars:{height:140,flexDirection:'row',alignItems:'flex-end',gap:5},day:{flex:1,alignItems:'center',gap:4},barPair:{height:110,flexDirection:'row',alignItems:'flex-end',gap:2},bar:{width:5,borderRadius:3},dayText:{fontSize:8,transform:[{rotate:'-45deg'}]}});